package com.app.episodic.utils

object LanguageConstants {
    private val languageMap = mapOf(
        "aa" to "Afar",
        "ab" to "Abjasio",
        "ae" to "Avéstico",
        "af" to "Afrikáans",
        "ak" to "Akan",
        "am" to "Amhárico",
        "an" to "Aragonés",
        "ar" to "Árabe",
        "as" to "Asamés",
        "av" to "Avar",
        "ay" to "Aimara",
        "az" to "Azerbaiyano",
        "ba" to "Bashkir",
        "be" to "Bielorruso",
        "bg" to "Búlgaro",
        "bi" to "Bislama",
        "bm" to "Bambara",
        "bn" to "Bengalí",
        "bo" to "Tibetano",
        "br" to "Bretón",
        "bs" to "Bosnio",
        "ca" to "Catalán",
        "ce" to "Checheno",
        "ch" to "Chamorro",
        "co" to "Corso",
        "cr" to "Cree",
        "cs" to "Checo",
        "cu" to "Eslavo",
        "cv" to "Chuvasio",
        "cy" to "Galés",
        "da" to "Danés",
        "de" to "Alemán",
        "dv" to "Divehi",
        "dz" to "Dzongkha",
        "ee" to "Ewe",
        "el" to "Griego",
        "en" to "Inglés",
        "eo" to "Esperanto",
        "es" to "Español",
        "et" to "Estonio",
        "eu" to "Euskera",
        "fa" to "Persa",
        "ff" to "Fulah",
        "fi" to "Finlandés",
        "fj" to "Fiyiano",
        "fo" to "Feroés",
        "fr" to "Francés",
        "fy" to "Frisón",
        "ga" to "Irlandés",
        "gd" to "Gaélico",
        "gl" to "Gallego",
        "gn" to "Guaraní",
        "gu" to "Guyaratí",
        "gv" to "Manés",
        "ha" to "Hausa",
        "he" to "Hebreo",
        "hi" to "Hindi",
        "ho" to "Hiri Motu",
        "hr" to "Croata",
        "ht" to "Criollo Haitiano",
        "hu" to "Húngaro",
        "hy" to "Armenio",
        "hz" to "Herero",
        "ia" to "Interlingua",
        "id" to "Indonesio",
        "ie" to "Interlingue",
        "ig" to "Igbo",
        "ii" to "Yi",
        "ik" to "Inupiaq",
        "io" to "Ido",
        "is" to "Islandés",
        "it" to "Italiano",
        "iu" to "Inuktitut",
        "ja" to "Japonés",
        "jv" to "Javanés",
        "ka" to "Georgiano",
        "kg" to "Kongo",
        "ki" to "Kikuyu",
        "kj" to "Kuanyama",
        "kk" to "Kazajo",
        "kl" to "Kalaallisut",
        "km" to "Jemer",
        "kn" to "Canarés",
        "ko" to "Coreano",
        "kr" to "Kanuri",
        "ks" to "Cachemir",
        "ku" to "Kurdo",
        "kv" to "Komi",
        "kw" to "Córnico",
        "ky" to "Kirguís",
        "la" to "Latín",
        "lb" to "Luxemburgués",
        "lg" to "Ganda",
        "li" to "Limburgués",
        "ln" to "Lingala",
        "lo" to "Lao",
        "lt" to "Lituano",
        "lu" to "Luba-Katanga",
        "lv" to "Letón",
        "mg" to "Malgache",
        "mh" to "Marshalés",
        "mi" to "Maorí",
        "mk" to "Macedonio",
        "ml" to "Malayalam",
        "mn" to "Mongol",
        "mr" to "Maratí",
        "ms" to "Malayo",
        "mt" to "Maltés",
        "my" to "Birmano",
        "na" to "Nauru",
        "nb" to "Noruego Bokmål",
        "nd" to "Ndebele",
        "ne" to "Nepalí",
        "ng" to "Ndonga",
        "nl" to "Neerlandés",
        "nn" to "Noruego Nynorsk",
        "no" to "Noruego",
        "nr" to "Ndebele",
        "nv" to "Navajo",
        "ny" to "Chichewa",
        "oc" to "Occitano",
        "oj" to "Ojibwa",
        "om" to "Oromo",
        "or" to "Oriya",
        "os" to "Osetio",
        "pa" to "Punyabí",
        "pi" to "Pali",
        "pl" to "Polaco",
        "ps" to "Pastún",
        "pt" to "Portugués",
        "qu" to "Quechua",
        "rm" to "Retorrománico",
        "rn" to "Rundi",
        "ro" to "Rumano",
        "ru" to "Ruso",
        "rw" to "Kinyarwanda",
        "sa" to "Sánscrito",
        "sc" to "Sardo",
        "sd" to "Sindhi",
        "se" to "Sami Septentrional",
        "sg" to "Sango",
        "sh" to "Serbocroata",
        "si" to "Cingalés",
        "sk" to "Eslovaco",
        "sl" to "Esloveno",
        "sm" to "Samoano",
        "sn" to "Shona",
        "so" to "Somalí",
        "sq" to "Albanés",
        "sr" to "Serbio",
        "ss" to "Suazi",
        "st" to "Sesoto",
        "su" to "Sundanés",
        "sv" to "Sueco",
        "sw" to "Suajili",
        "ta" to "Tamil",
        "te" to "Telugu",
        "tg" to "Tayiko",
        "th" to "Tailandés",
        "ti" to "Tigriña",
        "tk" to "Turcomano",
        "tl" to "Tagalo",
        "tn" to "Setswana",
        "to" to "Tongano",
        "tr" to "Turco",
        "ts" to "Tsonga",
        "tt" to "Tártaro",
        "tw" to "Twi",
        "ty" to "Tahitiano",
        "ug" to "Uigur",
        "uk" to "Ucraniano",
        "ur" to "Urdu",
        "uz" to "Uzbeko",
        "ve" to "Venda",
        "vi" to "Vietnamita",
        "vo" to "Volapük",
        "wa" to "Valón",
        "wo" to "Wolof",
        "xh" to "Xhosa",
        "xx" to "Sin Idioma",
        "yi" to "Yídish",
        "yo" to "Yoruba",
        "za" to "Zhuang",
        "zh" to "Chino Mandarín",
        "zu" to "Zulú"
    )

    fun getLanguageNameByCode(code: String): String {
        return languageMap[code.lowercase()] ?: code.uppercase()
    }

    fun getLanguageNameByCodeOrEnglish(code: String, englishName: String?): String {
        return languageMap[code.lowercase()] ?: englishName ?: code.uppercase()
    }
}
